apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekstaskcluster
  region: us-east-2

nodeGroups:
   - name: nodegroup1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: terraform_key_pair
   - name: nodegroup2
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: terraform_key_pair
   
